services:
  actualbudget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualbudget
    volumes:
      - /mnt/data/actualbudget:/data
    environment:
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=50
    networks:
      - docktail
    restart: unless-stopped
    labels:
      - docktail.service.enable=true
      - docktail.service.name=budget
      - docktail.service.port=5006
      - docktail.service.service-port=443

networks:
  docktail:
    name: docktail
    external: true
