services:
  actualbudget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualbudget
    networks:
      - tsbridge
    volumes:
      - /opt/actualbudget:/data
      - /opt/tsbridge/budget/certs:/certs
    environment:
      - ACTUAL_HTTPS_KEY=/certs/budget.fold-blenny.ts.net.key
      - ACTUAL_HTTPS_CERT=/certs/budget.fold-blenny.ts.net.crt
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=50
    labels:
      - tsbridge.enabled=true
      - tsbridge.service.name=budget
      - tsbridge.service.funnel_enabled=false
      - tsbridge.service.backend_addr=https://actualbudget:5006
      - tsbridge.service.insecure_skip_verify=true
      - tsbridge.service.ephemeral=false
    restart: unless-stopped
    ports:
      - 5006:5006
networks:
  tsbridge:
    name: tsbridge
    external: true
