services:
  actualbudget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actualbudget
    volumes:
      - /mnt/data/actualbudget:/data
      - /mnt/data/tsbridge/budget/certs:/certs
    environment:
      - ACTUAL_HTTPS_KEY=/certs/budget.${TS_TAILNET_NAME}.key
      - ACTUAL_HTTPS_CERT=/certs/budget.${TS_TAILNET_NAME}.crt
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=50
    networks:
      - tsbridge
    restart: unless-stopped
    labels:
      - tsbridge.enabled=true
      - tsbridge.service.name=budget
      - tsbridge.service.funnel_enabled=false
      - tsbridge.service.backend_addr=https://actualbudget:5006
      - tsbridge.service.insecure_skip_verify=true
      - tsbridge.service.ephemeral=true
networks:
  tsbridge:
    name: tsbridge
    external: true
