architecture: x86_64
config:
  image.architecture: amd64
  image.description: Debian trixie amd64 (20260302_05:24)
  image.os: Debian
  image.release: trixie
  image.serial: "20260302_05:24"
  image.type: squashfs
  image.variant: default
  security.nesting: "true"
  security.privileged: "false"
  security.protection.shift: "true"
devices:
  disk-device-1:
    path: /mnt/nvme
    shift: "true"
    source: /mnt/nvme
    type: disk
  docker-dotfiles:
    path: /opt/docker
    shift: "true"
    source: /home/sam/dotfiles/configs/docker
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  gpu-1:
    gputype: physical
    pci: "0000:00:02.0"
    type: gpu
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- bridged
stateful: false
description: debian 13 lxc
