# incus launch images:debian/13 debian-config < ./debian13lxc.yaml
architecture: x86_64
config:
  security.nesting: "true"
  security.privileged: "false"
  security.protection.shift: "true"
devices:
  docker-dotfiles:
    path: /opt/docker
    shift: "true"
    source: /home/sam/dotfiles/configs/docker
    type: disk
  eth0:
    name: eth0
    nictype: bridged
    parent: br0
    type: nic
  gpu-1:
    gputype: physical
    pci: "0000:00:02.0"
    type: gpu
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- bridged
stateful: false
description: debian 13 lxc
