services:
  plex:
    image: ghcr.io/hotio/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=32400/tcp
      - PLEX_CLAIM_TOKEN= # visit plex.tv/claim leave blank after initial claim
      - PLEX_ADVERTISE_URL=
      - PLEX_NO_AUTH_NETWORKS=192.168.1.0/24
      - PLEX_BETA_INSTALL=false
      - PLEX_PURGE_CODECS=false
    volumes:
      - /opt/plex:/config
      - /mnt/nvme:/pool
      - /tmp/plex:/transcode
    restart: unless-stopped
